server:
  port: 18086
spring:
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
    sentinel:
      transport:
        dashboard: localhost:8080
        port: 8719
  sleuth:
    sampler:
      probability: 1
  zipkin:
    base-url: http://localhost:9411
    sender:
      type: web
    discovery-client-enabled: false
  elasticsearch:
    rest:
      uris: http://192.168.80.180:9200
  jackson:
    default-property-inclusion: non_null #让@ResponseBody使用Jackson做反序列化时，过滤掉空的字段
feign:
  sentinel:
    enabled: true